version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/lmsdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVER=org.postgresql.Driver
      - SPRING_JPA_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - JWT_SECRET=localdevelopmentsecretkey
      - PORT=8080
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lmsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
